apiVersion: share.k8s.hirnkastl.com/v1beta1
kind: SmbShare
metadata:
  labels:
    app.kubernetes.io/name: smbshare
    app.kubernetes.io/instance: smbshare-sample
    app.kubernetes.io/part-of: smb-share-controller
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: smb-share-controller
  name: smbshare-sample
spec:
  # TODO(user): Add fields here
