name: Test 

on: pull_request

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - name: Install Krew and kuttl
        run: |
          KREW="krew-linux_amd64"
          curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz"
          tar zxvf "${KREW}.tar.gz"
          ./"${KREW}" install krew
          ./"${KREW}" install kuttl
          echo 'export PATH="${PATH}:${HOME}/.krew/bin"' >> ~/.bashrc
      - name: Run Tests
        run: ${HOME}/.krew/bin/kubectl-kuttl test --start-kind=false ./tests/e2e