name: Test 

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
jobs:
  build_and_push:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set Tag
        run: '[[ ${GITHUB_REF#refs/*/} =~ ^v[0-9]*.[0-9]*.[0-9]*$ ]] && echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV || echo "TAG=${{ github.sha }}" >> $GITHUB_ENV'
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Unit Test and build docker Image
        run: make docker-build IMG=ghcr.io/steveizzle/smb-share-controller:${{ env.TAG }}
      - name: Push docker Image
        run: make docker-push IMG=ghcr.io/steveizzle/smb-share-controller:${{ env.TAG }}
  integration-test:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Set Tag
        run: '[[ ${GITHUB_REF#refs/*/} =~ ^v[0-9]*.[0-9]*.[0-9]*$ ]] && echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV || echo "TAG=${{ github.sha }}" >> $GITHUB_ENV'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - name: Install Krew and kuttl
        run: |
          KREW="krew-linux_amd64"
          curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz"
          tar zxvf "${KREW}.tar.gz"
          ./"${KREW}" install krew
          ./"${KREW}" install kuttl
          echo 'export PATH="${PATH}:${HOME}/.krew/bin"' >> ~/.bashrc
      - name: Install Controller
        run: make deploy IMG=ghcr.io/steveizzle/smb-share-controller:${{ env.TAG }}
      - name: Run Kuttle Tests
        run: ${HOME}/.krew/bin/kubectl-kuttl test --start-kind=false ./tests/e2e
  release:
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false